models/availability.js, models/companies.js, models/employees.js, models/example.js, models/locations.js, models/requests.js
**What was changed**
1) Created Schems DB -- Just called it "project2Main" until we decide on an app name
2) Deleted example.js file
3) Created all the needed models for the database
=> Creating Models For Database

config/config.json, models/availability.js, models/companies.js, models/employees.js, package-lock.json, package.json
1) ID's are no longer named "id" but rather something like "CompanyNum"
- This will help joins to be consistent through the tables
2) Renamed some data points to be more specific
- This makes the table cols more easy to understand what actually goes inside them
=> Renaming model data points to be consistent

public/js/login-register.js, routes/apiRoutes.js, views/layouts/main.handlebars, views/login.handlebars
-------------------------
1) Whenever you click the login btn, it will try and create a walmart company into the db
-It makes sure that walmart already does not exists in the db
**What Needs To Change**
------------------------------
1) We obviously need to change the button that the click event is tied to. Currently it is the login-btn, but will need to change it whenever the carousel is finished
2) right now the company is currently hard coded as 'Walmart' and will need to change based on what the company the user is trying to create
=> Adds company to the db

models/companies.js, models/locations.js, public/js/login-register.js, routes/apiRoutes.js, views/newStore.handlebars
**What this changes**
------------------------
- UI
1) Added a button on the last page of the carousel that will act as the submit btn
- Backend
1) Whenever you submit the form, it checks to see if the company already exists in the db
- If not, then it will insert it
2) Creates a new location based on user input
- It makes sure the CompanyNum matches the company's db value
4) Add new apiRoutes
- "api/company/count/:name" just counts total value in db
- "api/company/find/:name" find the company value --
**This is how I get the Company Num**
3) Small model changes
- Added Zipcode to locations.js model
4) Small function changes
- Converted some of the apiRoutes functions to es6
- Will continue to do so as I use the routes
=> You can now create a comapany and location

public/styles/styles.css, views/managerView.handlebars, views/newStore.handlebars
In this pull request, I deleted the page from the carousel that asks if they would like to create more locations since that is now functioning from the manager view (I titled this "Manager Dashboard" but that can change). I also edited the text fields so that the placeholder text disappears when the user starts to use it.
On the manager dashboard, I created a navigation bar so that there would be a place for a logo, and a place to logout. 
I created a template for approving notifications with radio buttons.
If ya'll approve, I'll use this as a template to make the employee dashboard/view.
=> Manager view

routes/htmlRoutes.js, server.js, views/managerView.handlebars, views/partials/location-block.handlebars
This update is to add partials into our functionality. The four changes I made were:
1. The locations-block partial (locations-block.hbs)
2. The Manager View so we can see the partial (managerView.hbs)
3. HTML routes file so we have a route to the manager-page with the partial available (htmlRoutes.js)
4. An addition to our handlebars settings in the server.js file (server.js) to ensure that partials are running. 
Line 53 and down in managerView.hbs is now boilerplate and will be removed once we are able to pass data into our partial. 
Please let me know if you have questions about this or with partials!
=> partials updates

models/employees.js, public/js/login-register.js, routes/apiRoutes.js, views/newStore.handlebars
-------------------------
1) Edited Employee Model adding email and passwords
2) Adding input field for full name
3) The information entered on the account page now enters into the Employees table
**What We Need To Change**
---------------------------------
1) Maybe add a page for account info such as email, name and password separately than the company name
2) Right now, it automatically adds the employees Status as manager and PositionType as fulltime. We  will need to add inputs for these two categories
=> you can now create and employee account

public/styles/styles.css, views/login.handlebars, views/newStore.handlebars
I updated the Create Account Carousel by:
- Getting rid of the static button, and replacing it with individual arrow shaped buttons for each page of the carousel. This will allow us to validate the entries before allowing the user to go onto the next page. I will continue to work on giving them a more consistent position from one page to another
- I also split one long page into two pages: One for company name and password, another for the primary contact person info and their email address. 
- I shortened the minimum height of the carousel in response.
- I took away the table on the confirm information page, and left only the information they would need to confirm.
- I added an "edit" option that takes them back to the first page of the carousel.
And lastly, I changed the button on the …
=> updated newStore.handlebars

public/styles/styles.css, views/managerView.handlebars, views/newStore.handlebars
cleaned up create store functionality.
=> updated create store carousel

public/styles/styles.css, routes/apiRoutes.js, routes/htmlRoutes.js, views/managerView.handlebars, views/partials/availability.handlebars, views/partials/location-block.handlebars
edited partials to make availability work. added dummy data to get dates to start with.
=> added availability partial

public/styles/styles.css, routes/apiRoutes.js, routes/htmlRoutes.js, views/employeeView.handlebars, views/managerView.handlebars
Fixed issues with divs, employee dashboard should be fully functional
=> Employee view

models/employees.js, public/js/login-register.js, routes/apiRoutes.js
--------------------------
Fixes the problem for adding the employee info to the DB
=> Fixed Adding Employee To DB

package-lock.json, package.json, public/styles/styles.css, routes/apiRoutes.js, routes/htmlRoutes.js, views/managerView.handlebars, views/partials/employee-block.handlebars, views/partials/location-block.handlebars
I have been working on the functionality for partials. I am really close! I am getting data to pass back and forth to the database and I am getting partials to appear to the page, but no data :( I'd love help here. 
Here is my main HTML route: 
Here is the partial itself. I know the part I have wrong is in the curly brackets. I am receiving too many partials appearing on the page, so perhaps there is something else I should be inputting. 
Here's what I'm getting on the front-end. As you can see, the last partial, I am getting an id!
=> partial functionality. not fully resolved but hoping it is close

public/styles/styles.css, views/login.handlebars
=> Rework login ui

public/js/add-employee.js, public/styles/styles.css, routes/apiRoutes.js, views/managerView.handlebars
-------------------------
1) Adds availability dropdown to the 'Add New Employee Modal'
2) When you click the 'Add Employee' btn it will....
- Add new employee to db
- Get that employeenum fron the db
- Inserts all the info in the availability db
=> Adding Availability To DB

public/styles/styles.css, views/layouts/main.handlebars, views/managerView.handlebars, views/partials/employee-block.handlebars
1) Changed font to Rubik. This can change was just a test. 
2) Updated margin-top for employee listing. It felt a little low at 100px down. <img width="978" alt="Screen Shot 2019-12-26 at 5 58 04 PM" src="https://user-images.githubusercontent.com/49762109/71493986-61de5980-2809-11ea-99c7-22750d213a76.png">
3) Updated Employee Modal. Some styles still pending [https://drive.google.com/file/d/1fEnTiAa8HAdlbWtMSTEgzLT1ToDbeTaK/view?usp=sharing](url)
=> style changes including font changes// changes to employee add modal //

models/schedule.js, public/styles/styles.css, routes/htmlRoutes.js, views/managerView.handlebars
-------------------------
1) Created a schedule model. Each employee should get a 2 week schedule
- Time will be entered as military time ex: 04-18
2) On the schedule page, you will click the plus and it will show a new menu at the bottom of the page
- Here you can dynamically add new shifts and the number of employees needed for that shift
- The schedule will be generate based on the shifts entered here
**What needs to change**
-----------------------------
1) I will work on the auto generating schedule portion after this pr
2) Maybe instead of having and input field when creating a new shift, it creates a dropdown that way the client can show and hide shifts 
3) Removing shifts. Create a little minus button next to the shift that will allow you to delete that shift
=> Being Able To Add Shifts

models/requests.js, public/js/dashboard.js, views/employeeView.handlebars
This is an update to the employee dashboard.
Updated the aesthetic to reflect the new theme. It includes a form for employees to make requests. 
I updated the request model. Here was my thinking:
I added the boolean values of isApproved and isDenied, because I thought that they would both be submitted to the database with a default of "false". If both isApproved and isDenied are both false, using an each/if handlebars statement, the request appears in the notification panel of the Manager dashboard.  The manager will then have the option to approve or deny the request, and submit it back to the database updated with either Is Approved or is Denied = true. Using an each/if statement for the employee dashboard, if isApproved or isDenied =true, the employee is notified of the manager's …
=> Employee view2

views/managerView.handlebars
This should be the commit i talked about that reverts us back to the majority of our changes before we left Roasterie. Please check this and see if it runs properly for you.
=> small change

config/config.json, public/js/dashboard.js, routes/apiRoutes.js, routes/htmlRoutes.js
=> locations now appears
